# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phylogeorecdialog.ui'
#
# Created: Mon Jul 18 17:53:54 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PhyloGeoRecDialogBase(object):
    def setupUi(self, PhyloGeoRecDialogBase):
        PhyloGeoRecDialogBase.setObjectName(_fromUtf8("PhyloGeoRecDialogBase"))
        PhyloGeoRecDialogBase.setEnabled(True)
        PhyloGeoRecDialogBase.resize(760, 507)
        PhyloGeoRecDialogBase.setMaximumSize(QtCore.QSize(760, 507))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PhyloGeoRec/icons/icon24x24.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PhyloGeoRecDialogBase.setWindowIcon(icon)
        PhyloGeoRecDialogBase.setSizeGripEnabled(True)
        PhyloGeoRecDialogBase.setModal(False)
        self.tabWidget = QtGui.QTabWidget(PhyloGeoRecDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 741, 491))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.cmdGenGeo = QtGui.QPushButton(self.tab)
        self.cmdGenGeo.setGeometry(QtCore.QRect(590, 410, 131, 51))
        self.cmdGenGeo.setObjectName(_fromUtf8("cmdGenGeo"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 400, 561, 61))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lineEdit_GeoPath = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_GeoPath.setGeometry(QtCore.QRect(150, 20, 321, 21))
        self.lineEdit_GeoPath.setObjectName(_fromUtf8("lineEdit_GeoPath"))
        self.cmdBrwGeoPath = QtGui.QPushButton(self.groupBox_5)
        self.cmdBrwGeoPath.setGeometry(QtCore.QRect(480, 20, 75, 23))
        self.cmdBrwGeoPath.setObjectName(_fromUtf8("cmdBrwGeoPath"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 719, 381))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox = QtGui.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 691, 341))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEdit_Phylo = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_Phylo.setGeometry(QtCore.QRect(60, 21, 541, 20))
        self.lineEdit_Phylo.setObjectName(_fromUtf8("lineEdit_Phylo"))
        self.cmdBrwPhylo = QtGui.QPushButton(self.groupBox)
        self.cmdBrwPhylo.setGeometry(QtCore.QRect(610, 20, 75, 23))
        self.cmdBrwPhylo.setObjectName(_fromUtf8("cmdBrwPhylo"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 691, 341))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.lineEdit_RelationTablePath = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_RelationTablePath.setGeometry(QtCore.QRect(120, 20, 481, 21))
        self.lineEdit_RelationTablePath.setObjectName(_fromUtf8("lineEdit_RelationTablePath"))
        self.cmdBrwRelationTable = QtGui.QPushButton(self.groupBox_4)
        self.cmdBrwRelationTable.setGeometry(QtCore.QRect(610, 20, 75, 23))
        self.cmdBrwRelationTable.setObjectName(_fromUtf8("cmdBrwRelationTable"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.tableView_Relation = QtGui.QTableView(self.groupBox_4)
        self.tableView_Relation.setGeometry(QtCore.QRect(10, 50, 671, 281))
        self.tableView_Relation.setObjectName(_fromUtf8("tableView_Relation"))
        self.tableView_Relation.horizontalHeader().setSortIndicatorShown(False)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 410, 701, 51))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 380, 701, 25))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_13.setSpacing(3)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.toolButton_Settings = QtGui.QToolButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PhyloGeoRec/icons/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Settings.setIcon(icon1)
        self.toolButton_Settings.setObjectName(_fromUtf8("toolButton_Settings"))
        self.horizontalLayout_13.addWidget(self.toolButton_Settings)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_13.addWidget(self.progressBar)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_MessageIcon = QtGui.QLabel(self.layoutWidget)
        self.label_MessageIcon.setMaximumSize(QtCore.QSize(32, 32))
        self.label_MessageIcon.setText(_fromUtf8(""))
        self.label_MessageIcon.setMargin(2)
        self.label_MessageIcon.setObjectName(_fromUtf8("label_MessageIcon"))
        self.horizontalLayout_14.addWidget(self.label_MessageIcon)
        self.label_Status = QtGui.QLabel(self.layoutWidget)
        self.label_Status.setText(_fromUtf8(""))
        self.label_Status.setObjectName(_fromUtf8("label_Status"))
        self.horizontalLayout_14.addWidget(self.label_Status)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_14)
        self.pushButton_Run = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Run.sizePolicy().hasHeightForWidth())
        self.pushButton_Run.setSizePolicy(sizePolicy)
        self.pushButton_Run.setDefault(True)
        self.pushButton_Run.setObjectName(_fromUtf8("pushButton_Run"))
        self.horizontalLayout_13.addWidget(self.pushButton_Run)
        self.pushButton_Close = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Close.sizePolicy().hasHeightForWidth())
        self.pushButton_Close.setSizePolicy(sizePolicy)
        self.pushButton_Close.setObjectName(_fromUtf8("pushButton_Close"))
        self.horizontalLayout_13.addWidget(self.pushButton_Close)
        self.pushButton_Help = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Help.sizePolicy().hasHeightForWidth())
        self.pushButton_Help.setSizePolicy(sizePolicy)
        self.pushButton_Help.setObjectName(_fromUtf8("pushButton_Help"))
        self.horizontalLayout_13.addWidget(self.pushButton_Help)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(19, 330, 702, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 350, 701, 22))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.lineEdit_OutputFilename = QtGui.QLineEdit(self.layoutWidget_2)
        self.lineEdit_OutputFilename.setObjectName(_fromUtf8("lineEdit_OutputFilename"))
        self.horizontalLayout_15.addWidget(self.lineEdit_OutputFilename)
        self.toolButton_Browse = QtGui.QToolButton(self.layoutWidget_2)
        self.toolButton_Browse.setObjectName(_fromUtf8("toolButton_Browse"))
        self.horizontalLayout_15.addWidget(self.toolButton_Browse)
        self.layoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 10, 701, 22))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.formLayout_7 = QtGui.QFormLayout(self.layoutWidget_3)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.comboBox_Template = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Template.sizePolicy().hasHeightForWidth())
        self.comboBox_Template.setSizePolicy(sizePolicy)
        self.comboBox_Template.setObjectName(_fromUtf8("comboBox_Template"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_Template)
        self.label_9 = QtGui.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.splitter = QtGui.QSplitter(self.tab_2)
        self.splitter.setGeometry(QtCore.QRect(20, 40, 702, 281))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeWidget = QtGui.QTreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget.header().setVisible(False)
        self.scrollArea = QtGui.QScrollArea(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 279))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_17 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.propertyPagesContainer = QtGui.QVBoxLayout()
        self.propertyPagesContainer.setObjectName(_fromUtf8("propertyPagesContainer"))
        self.textBrowser = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setStyleSheet(_fromUtf8("background-color:rgba(0, 0, 0, 0);"))
        self.textBrowser.setFrameShape(QtGui.QFrame.NoFrame)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.propertyPagesContainer.addWidget(self.textBrowser)
        self.gridLayout_17.addLayout(self.propertyPagesContainer, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(180, 20, 541, 234))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 150, 234))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PhyloGeoRec/icons/icon150x150.png")))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_19 = QtGui.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(150, 780, 155, 13))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser_2.setEnabled(True)
        self.textBrowser_2.setGeometry(QtCore.QRect(180, 270, 541, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        self.textBrowser_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(180, 340, 541, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_3.sizePolicy().hasHeightForWidth())
        self.textBrowser_3.setSizePolicy(sizePolicy)
        self.textBrowser_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(10, 280, 161, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(10, 350, 161, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.textEdit_Phylo = QtGui.QTextEdit(PhyloGeoRecDialogBase)
        self.textEdit_Phylo.setGeometry(QtCore.QRect(470, 510, 104, 71))
        self.textEdit_Phylo.setObjectName(_fromUtf8("textEdit_Phylo"))
        self.textEdit_Coords = QtGui.QTextEdit(PhyloGeoRecDialogBase)
        self.textEdit_Coords.setGeometry(QtCore.QRect(470, 610, 104, 71))
        self.textEdit_Coords.setObjectName(_fromUtf8("textEdit_Coords"))

        self.retranslateUi(PhyloGeoRecDialogBase)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PhyloGeoRecDialogBase)

    def retranslateUi(self, PhyloGeoRecDialogBase):
        PhyloGeoRecDialogBase.setWindowTitle(_translate("PhyloGeoRecDialogBase", "PhyloGeoRec: Phylogeography Reconstruction Tool", None))
        self.cmdGenGeo.setText(_translate("PhyloGeoRecDialogBase", "Generate\n"
" Geophylogeny Model", None))
        self.groupBox_5.setTitle(_translate("PhyloGeoRecDialogBase", "Output Geophylogeny Model Folder Path", None))
        self.cmdBrwGeoPath.setText(_translate("PhyloGeoRecDialogBase", "Browse", None))
        self.label_23.setText(_translate("PhyloGeoRecDialogBase", "Geophylogeny Model Path", None))
        self.groupBox.setTitle(_translate("PhyloGeoRecDialogBase", "Phylogenetic Tree", None))
        self.cmdBrwPhylo.setText(_translate("PhyloGeoRecDialogBase", "Browse", None))
        self.label_6.setText(_translate("PhyloGeoRecDialogBase", "Tree File", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("PhyloGeoRecDialogBase", "Phylogenetic Tree", None))
        self.groupBox_4.setTitle(_translate("PhyloGeoRecDialogBase", "Taxa - Coordinate Relationship Table", None))
        self.cmdBrwRelationTable.setText(_translate("PhyloGeoRecDialogBase", "Browse", None))
        self.label_17.setText(_translate("PhyloGeoRecDialogBase", "Relationship Table File", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("PhyloGeoRecDialogBase", "Spatial Layer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PhyloGeoRecDialogBase", "Geophylogeny Builder", None))
        self.plainTextEdit.setPlainText(_translate("PhyloGeoRecDialogBase", "QGIS2threejs. Copyright (c) 2013-2015 Minoru Akagi.  The distribution of the program is granted provided no charge is made and the copyright notice is included.  Proper attribution of the author as the source of the software would be appreciated: \n"
"Akagi, M. 2015. QGIS2threejs. Version 1.4. https://plugins.qgis.org/plugins/Qgis2threejs/version/1.4/", None))
        self.toolButton_Settings.setText(_translate("PhyloGeoRecDialogBase", "...", None))
        self.progressBar.setFormat(_translate("PhyloGeoRecDialogBase", "%p%", None))
        self.pushButton_Run.setText(_translate("PhyloGeoRecDialogBase", "Run", None))
        self.pushButton_Close.setText(_translate("PhyloGeoRecDialogBase", "Close", None))
        self.pushButton_Help.setToolTip(_translate("PhyloGeoRecDialogBase", "Open local help file with default browser.", None))
        self.pushButton_Help.setText(_translate("PhyloGeoRecDialogBase", "Help", None))
        self.label_4.setText(_translate("PhyloGeoRecDialogBase", "Output HTML file path", None))
        self.toolButton_Browse.setText(_translate("PhyloGeoRecDialogBase", "Browse...", None))
        self.label_9.setText(_translate("PhyloGeoRecDialogBase", "Template file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PhyloGeoRecDialogBase", "3D Model Builder", None))
        self.label.setText(_translate("PhyloGeoRecDialogBase", "PHYLOGEOrec: QGIS plugin for Phylogeography Reconstruction.\n"
"\n"
"Version 1.0 (Beta 7.5)\n"
"\n"
"Copyright (C) 2016  Maulana Malik Nashrulloh\n"
"Copyright (C) 2016  Nia Kurniawan\n"
"Copyright (C) 2016  NKResearch Lab\n"
"\n"
"This program is free software; you can redistribute it and/or modify it under the terms of the\n"
"GNU General Public License as published by the Free Software Foundation; either version 2\n"
"of the License, or (at your option) any later version.\n"
"\n"
"This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the\n"
"implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n"
"See the GNU General Public License for more details.\n"
"\n"
"You should have received a copy of the GNU General Public License along with this program; if not, write to the \n"
"Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.", None))
        self.label_19.setText(_translate("PhyloGeoRecDialogBase", "This Program should be cited as:", None))
        self.textBrowser_2.setHtml(_translate("PhyloGeoRecDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Nashrulloh, M.M., &amp; N. Kurniawan. 2016. </span><span style=\" font-size:8pt; font-weight:600;\">PHYLOGEORec: QGIS Plugin for Phylogeography Reconstruction. Version 1.0 (Beta 7.5)</span><span style=\" font-size:8pt;\">. Department of Biology. Faculty of Mathematics and Natural Sciences. Brawijaya University. Malang.</span></p></body></html>", None))
        self.textBrowser_3.setHtml(_translate("PhyloGeoRecDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Nashrulloh, M.M. &amp; N. Kurniawan. 2016.</span><span style=\" font-size:8pt; font-weight:600;\"> Development of PHYLOGEORec 1.0: QGIS Plugin for Reconstructing Phylogeography and Its Implementation in Reconstructing Phylogeography of Limnonectes in Sulawesi</span><span style=\" font-size:8pt;\">. Department of Biology. Faculty of Mathematics and Natural Sciences. Brawijaya University. Malang. Undergraduate Thesis. </span></p></body></html>", None))
        self.label_7.setText(_translate("PhyloGeoRecDialogBase", "This Program Should be cited as:", None))
        self.label_14.setText(_translate("PhyloGeoRecDialogBase", "Citation:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PhyloGeoRecDialogBase", "About", None))

import resources_rc
